name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Test code format
        run: |
          pip3 install autopep8
          autopep8 --diff --exit-code --max-line-length 128 --recursive videocore6
